rule degs2gmt:
    input:
        degs = "degs.csv"
    output:
        output = "degs.gmt"
    params:
        gene_col = "HGNC.symbol",
        fc_col = "log2FoldChange",
        comp_col = "group",
        pv_col = "padj",
        pv_cutoff = 0.1,
        fc_cutoff = 0
    wrapper: "file://.."
